// Copyright (c) 2025 The GPU-Miner Authors. All rights reserved.
// Use of this source code is governed by a GPL-3.0-style license that can be
// found in the LICENSE file.

#ifndef MINING_JOB_H_
#define MINING_JOB_H_

#include <string>
#include <vector>

// Represents a job received from the pool. All fields are kept as hex strings
// as they are received, to be converted to binary format by the algorithm.
struct MiningJob {
    std::string job_id;
    std::string prev_hash;
    std::string coinb1;
    std::string coinb2;
    std::vector<std::string> merkle_branches;
    std::string version;
    std::string nbits;
    std::string ntime;
    bool clean_jobs;

    std::string extranonce1;
    std::string extranonce2; // The hex string generated by the miner thread
};

#endif // MINING_JOB_H_